name: Check PR Approval on New Commits

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  check-approval:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Extract Pull Request Number (if available)
      - name: Get PR Number
        id: get-pr-number
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            pr_number=$(echo "${{ github.event.pull_request.number }}")
          else
            pr_number=""
          fi
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          echo "Pull Request Number: $pr_number"

      # Step 3: Get latest commit timestamp
      - name: Get latest commit timestamp
        id: latest-commit
        run: |
          commit_sha=$(git rev-parse HEAD)
          commit_timestamp=$(gh api graphql -f query='
          {
            repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
              object(expression: "${commit_sha}") {
                ... on Commit {
                  committedDate
                }
              }
            }
          }' --jq '.data.repository.object.committedDate')
          echo "COMMIT_TIMESTAMP=$commit_timestamp" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Get approval timestamp
      - name: Get approval timestamp
        id: get-approval
        run: |
          if [ -z "${{ env.PR_NUMBER }}" ]; then
            echo "No associated pull request found."
            exit 1
          fi

          approval_timestamp=$(gh api graphql -f query='
          {
            repository(owner: "${{ github.repository_owner }}", name: "${{ github.event.repository.name }}") {
              pullRequest(number: '"${{ env.PR_NUMBER }}"') {
                reviews(last: 1, states: APPROVED) {
                  nodes {
                    createdAt
                  }
                }
              }
            }
          }' --jq '.data.repository.pullRequest.reviews.nodes[0].createdAt')

          echo "APPROVAL_TIMESTAMP=$approval_timestamp" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 5: Compare the timestamps
      - name: Compare timestamps
        id: compare-timestamps
        run: |
          if [[ "${{ env.COMMIT_TIMESTAMP }}" > "${{ env.APPROVAL_TIMESTAMP }}" ]]; then
            echo "New commit was pushed after approval. Dismissing approval."
            exit 1
          else
            echo "No new commit after approval."
          fi
        env:
          COMMIT_TIMESTAMP: ${{ env.COMMIT_TIMESTAMP }}
          APPROVAL_TIMESTAMP: ${{ env.APPROVAL_TIMESTAMP }}

      # Step 6: (Optional) Notify if approval is invalid
      - name: Notify team about invalid approval
        if: failure()
        run: |
          echo "New commit detected after approval. Notify the team!"
